### ISSUE TITLE
Instructions on peer Feedback

### ISSUE THREAD

**Issue by ratnanil** [ComputationalMovementAnalysis/FS21#41]
Hey Nikos! I just created a new brach `peer` where I added instructions on how the students should provide peer feedback on exercise 3. Can you have a look at these instructions and tell me what you think of it? You can also just push changes or make a pull request.. whatever you like. 

In that branch, the _bookdown.yaml has only the necessary files, so you can preview the instructions locally without having to build the whole book.

https://github.com/ComputationalMovementAnalysis/FS21/tree/peer

Two important things:
- Can you install the newest version of inlineComments and see if everything works for you?
- Can work on the "todo" i have placed in the instruction?

**Comment by ratnanil** [comment]
@KimboGilda : I completely forgot you don't work Thursdays! I just had a talk with @plaubezhaw : We will make the peer feedback optional, and for week 4 rather that week 3. Can you have a look at my pull request an merge it and rebuild the book if you dont have any issues? dont merge bookdown.yaml however.

> Can work on the "todo" i have placed in the instruction?

this is deprecated

**Comment by KimboGilda** [comment]
Hi Nils. I just saw your input. I will try to integrate everything first thing tomorrow morning.
